---

- name: Add nginx yum repo
  yum_repository:
    name: nginx repo
    description: official nginx yum repo
    baseurl: 'http://nginx.org/packages/centos/{{ ansible_distribution_major_version }}/amd64'
    gpgcheck: false
    state: present
  when: ansible_distribution == "CentOS"


- name: Add nginx yum repo
  yum_repository:
    name: nginx repo
    description: official nginx yum repo
    baseurl: 'http://nginx.org/packages/rhel/{{ ansible_distribution_major_version }}/amd64'
    gpgcheck: false
    state: present
  when: ansible_distribution == "RedHat"

- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Copy nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure nginx default configuration files are deleted
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/nginx/conf.d/default.conf"
    - "/etc/nginx/conf.d/ssl.conf"
    - "/etc/nginx/conf.d/virtual.conf"

- name: Start and enable nginx 
  service: 
    name: nginx
    state: started
    enabled: yes


# vim:ft=ansible:
